<?php

declare(strict_types=1);

namespace Asignua\FilamentSeoFiles\Support;

use RuntimeException;

/**
 * Thrown when a public file is already being generated by another process (the nightly
 * schedule, a panel click, a second console run).
 */
class GenerationInProgress extends RuntimeException {}
