<?php

declare(strict_types=1);

namespace Asignua\FilamentSeoFiles\Support;

use Closure;
use Filament\Facades\Filament;
use Filament\Panel;
use Illuminate\Auth\AuthManager;
use Illuminate\Contracts\Auth\Guard;
use Illuminate\Support\Facades\App;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Cache;

/**
 * Runs a closure the way the scheduler would: no Filament panel, no tenant, no logged-in
 * user, and (optionally) in the language of the file being built.
 *
 * The files end up in the web root, i.e. they are PUBLIC. A panel click generates them inside
 * the admin's Livewire request, where Filament adds the tenancy scope to tenant-scoped
 * models and any global scope that reads `auth()->user()` (drafts, role-gated records) shows
 * the admin more than a visitor may see. Without this the files would differ depending on who
 * regenerated them last.
 */
final class PublicContext
{
    /**
     * @template T
     *
     * @param Closure(): T $callback
     *
     * @return T
     */
    public static function run(Closure $callback, ?string $locale = null): mixed
    {
        $panel = Filament::getCurrentPanel();
        $tenant = Filament::getTenant();
        $previousLocale = App::getLocale();

        // Hiding the user is not enough for a SessionGuard (it re-reads the id from the session),
        // so EVERY guard a scope or Filament could ask for (`auth()`, `auth('<name>')`,
        // `Filament::auth()` with its fallback to the default panel's guard) is replaced by a
        // guard with nobody in it. The resolved instances are put back untouched afterwards
        // (an in-memory `actingAs()` user included).
        $manager = Auth::getFacadeRoot();
        $resolved = self::resolvedGuards($manager);
        $names = array_unique([
            ...array_keys((array) config('auth.guards', [])),
            $manager->getDefaultDriver(),
            ...array_map(static fn (Panel $each): string => $each->getAuthGuard(), array_values(Filament::getPanels())),
        ]);
        $nobody = new NullGuard;
        self::setResolvedGuards($manager, [...$resolved, ...array_fill_keys($names, $nobody)]);

        try {
            Filament::setTenant(null, isQuiet: true);
            Filament::setCurrentPanel(null);

            if ($locale !== null) {
                App::setLocale($locale);
            }

            return $callback();
        } finally {
            App::setLocale($previousLocale);
            self::setResolvedGuards($manager, $resolved);
            Filament::setCurrentPanel($panel);
            Filament::setTenant($tenant, isQuiet: true);
        }
    }

    /**
     * @return array<string, Guard>
     */
    private static function resolvedGuards(AuthManager $manager): array
    {
        return (fn (): array => $this->guards)->call($manager);
    }

    /**
     * @param array<string, Guard> $guards
     */
    private static function setResolvedGuards(AuthManager $manager, array $guards): void
    {
        (function () use ($guards): void {
            $this->guards = $guards;
        })->call($manager);
    }

    /**
     * Runs the closure under a non-blocking cache lock, so a panel click cannot interleave
     * with the nightly run (two runs deleting each other's stale parts).
     *
     * @template T
     *
     * @param Closure(): T $callback
     *
     * @throws GenerationInProgress
     *
     * @return T
     */
    public static function exclusive(string $name, Closure $callback): mixed
    {
        $lock = Cache::lock('filament-seo-files:generate:'.$name, 3600);

        if (!$lock->get()) {
            throw new GenerationInProgress("{$name} is already being generated by another process — try again in a minute.");
        }

        try {
            return $callback();
        } finally {
            $lock->release();
        }
    }
}
